# This workflow will run unit tests

name: Run Unit Tests
on:
  push:
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      matrix:
        python-version: [ 3.6, 3.8 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install holmesv
          pip install -r requirements.txt
          sudo apt install -y libsndfile1
      - name: Test Mozilla TTS
        run: |
          pip install pytest pytest-timeout
          pytest tests/test_mtts.py --junitxml=tests/tts-test-results.xml
      - name: Upload TTS test results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results-3.6
          path: tests/tts-test-results.xml
        if: ${{ always() }}
